import { useCallback } from 'react';
import { usePreferences } from './usePreferences';

const ar: Record<string, string> = {
  All: 'الكل', Upgrades: 'الترقيات', Boosts: 'التعزيزات', Skins: 'المظاهر', Energy: 'الطاقة', Home: 'الرئيسية', Game: 'اللعبة', Inventory: 'الممتلكات', Missions: 'المهام', Wallet: 'المحفظة', Profile: 'الملف الشخصي',
  'Invite Friends': 'دعوة الأصدقاء', 'Daily Reward': 'المكافأة اليومية', Store: 'المتجر', Leaderboard: 'لوحة الصدارة', History: 'السجل', Settings: 'الإعدادات',
  'Telegram Mini App': 'تطبيق تيليجرام المصغّر', 'Tap. Earn. Level up.': 'انقر، اربح، وتقدّم.', 'Your current balance is': 'رصيدك الحالي هو', 'Play MTX': 'ابدأ اللعب', 'MTX features': 'ميزات MTX',
  'Item categories': 'فئات المنتجات', 'Primary navigation': 'التنقل الرئيسي', Close: 'إغلاق', Boost: 'تعزيز', Earn: 'اربح', hour: 'ساعة', 'Tap MTX coin': 'انقر على عملة MTX',
  '⚡ Boost & Upgrades': '⚡ التعزيزات والترقيات', 'Open Upgrade Store': 'فتح متجر الترقيات', 'Open Inventory · Use boosts': 'فتح الممتلكات · استخدام التعزيزات', 'Permanent upgrades are purchased securely from the server. Consumable boosts are used from Inventory.': 'تُشترى الترقيات الدائمة بأمان من الخادم، وتُستخدم التعزيزات الاستهلاكية من الممتلكات.',
  '🎯 Earn Tasks': '🎯 مهام الربح', 'Choose an available task to earn MTX rewards.': 'اختر مهمة متاحة للحصول على مكافآت MTX.', Open: 'فتح',
  Day: 'اليوم', days: 'أيام', 'Current streak': 'سلسلة الحضور الحالية', 'Claim reward': 'استلام المكافأة', 'Come back tomorrow': 'عُد غدًا', 'Daily Combo': 'المجموعة اليومية', 'Daily Cipher': 'الرمز اليومي', 'Enter three item IDs separated by commas.': 'أدخل معرّفات ثلاثة منتجات مفصولة بفواصل.', Claim: 'استلام', Claimed: 'تم الاستلام', 'Decode for': 'فك الرمز مقابل',
  'Activity History': 'سجل النشاط', 'Purchases, upgrades, payments and rewards': 'المشتريات والترقيات والمدفوعات والمكافآت', 'History filters': 'مرشحات السجل', Purchases: 'المشتريات', Payments: 'المدفوعات', Rewards: 'المكافآت', 'Permanent upgrade': 'ترقية دائمة', 'Store purchase': 'شراء من المتجر', payment: 'دفعة', 'No credit': 'لم يُضف رصيد', 'Verified server reward': 'مكافأة مؤكدة من الخادم', completed: 'مكتمل', confirmed: 'مؤكد', pending: 'قيد الانتظار', claimed: 'تم الاستلام', 'Open MTX inside Telegram to view your private history.': 'افتح MTX داخل تيليجرام لعرض سجلك الخاص.', 'Loading your history…': 'جارٍ تحميل السجل…', 'No activity in this category yet.': 'لا يوجد نشاط في هذه الفئة بعد.', Retry: 'إعادة المحاولة',
  'Owned skins, boosts and consumables': 'المظاهر والتعزيزات والعناصر الاستهلاكية التي تملكها', items: 'عناصر', 'Newest first': 'الأحدث أولًا', 'Oldest first': 'الأقدم أولًا', 'No owned items in this category.': 'لا تملك عناصر في هذه الفئة.', Aurora: 'الشفق', 'Recharge boost': 'تعزيز إعادة الشحن', 'Energy cell': 'خلية طاقة', 'One-time use: fills energy to maximum.': 'استخدام لمرة واحدة: يملأ الطاقة بالكامل.', 'One-time use: restores 25% maximum energy.': 'استخدام لمرة واحدة: يستعيد 25٪ من الحد الأقصى للطاقة.', 'Permanent cosmetic: changes the MTX coin appearance.': 'مظهر دائم يغيّر شكل عملة MTX.', Quantity: 'الكمية', 'Saving taps…': 'جارٍ حفظ النقرات…', 'Use once · Refill energy': 'استخدام · ملء الطاقة', 'Use once · Restore 25%': 'استخدام · استعادة 25٪', 'Saving…': 'جارٍ الحفظ…', 'Equipped · Use default': 'مفعّل · العودة للافتراضي', 'Equip Aurora': 'تفعيل الشفق', 'Load more': 'عرض المزيد', 'Purchase history': 'سجل المشتريات', 'Saving pending taps before using item…': 'جارٍ حفظ النقرات المعلّقة قبل الاستخدام…', 'Recharge used once. Energy is now full.': 'تم استخدام التعزيز وامتلأت الطاقة.', 'Energy Cell used once. 25% energy restored.': 'تم استخدام خلية الطاقة واستعادة 25٪.', 'Activation failed.': 'فشل التفعيل.', 'Saving skin selection…': 'جارٍ حفظ اختيار المظهر…', 'Aurora Skin equipped.': 'تم تفعيل مظهر الشفق.', 'Default MTX appearance restored.': 'تمت استعادة مظهر MTX الافتراضي.', 'Skin selection failed.': 'فشل اختيار المظهر.',
  'Live updates': 'تحديثات مباشرة', 'Updating every 5 seconds': 'يتم التحديث كل 5 ثوانٍ', 'Daily, weekly and monthly progress': 'التقدم اليومي والأسبوعي والشهري', Level: 'المستوى', Items: 'العناصر', Referrals: 'الإحالات', 'Profit per tap': 'ربح كل نقرة', 'Profit per hour': 'الربح في الساعة',
  'Invite friends': 'دعوة الأصدقاء', 'Your code': 'رمزك', 'Telegram session required': 'يلزم فتح جلسة تيليجرام', 'Copy invite link': 'نسخ رابط الدعوة', Invited: 'المدعوون', 'MTX earned': 'أرباح MTX', 'Referral code': 'رمز الدعوة', 'Apply code': 'تطبيق الرمز', 'Self-referral and repeated device fingerprints are rejected.': 'يتم رفض الإحالة الذاتية وتكرار استخدام الجهاز.', 'Referral service is temporarily unavailable.': 'خدمة الدعوات غير متاحة مؤقتًا.', 'Connecting securely to Telegram…': 'جارٍ الاتصال بتيليجرام بأمان…', 'Telegram authentication failed. Close and reopen the Mini App.': 'فشلت مصادقة تيليجرام. أغلق التطبيق المصغّر وافتحه مجددًا.', 'Open MTX from @TOKXTAPBOT to enable referrals.': 'افتح MTX من @TOKXTAPBOT لتفعيل الدعوات.', 'This referral code could not be accepted.': 'تعذّر قبول رمز الدعوة هذا.',
  Language: 'اللغة', 'Interface language': 'لغة الواجهة', Appearance: 'المظهر', 'Color theme': 'سمة الألوان', System: 'النظام', Dark: 'داكن', Light: 'فاتح', 'Game feedback': 'استجابة اللعبة', 'Tap sound': 'صوت النقر', 'Play a short sound for each tap': 'تشغيل صوت قصير لكل نقرة', Vibration: 'الاهتزاز', 'Telegram haptic feedback while tapping': 'اهتزاز تيليجرام أثناء النقر', 'Low-power mode': 'وضع توفير الطاقة', 'Reduce motion, glow and background effects': 'تقليل الحركة والتوهج وتأثيرات الخلفية', 'Saved automatically on this device': 'يتم الحفظ تلقائيًا على هذا الجهاز',
  'Server-priced items and upgrades': 'منتجات وترقيات بأسعار يحددها الخادم', 'Open MTX inside Telegram to use the secure store.': 'افتح MTX داخل تيليجرام لاستخدام المتجر الآمن.', 'Waking up the Store server…': 'جارٍ تشغيل خادم المتجر…', 'More filters': 'مرشحات إضافية', 'Search store': 'البحث في المتجر', 'Search items': 'البحث عن منتج', 'Sort store items': 'ترتيب المنتجات', 'Featured first': 'المميّزة أولًا', 'Lowest price': 'الأقل سعرًا', 'Highest price': 'الأعلى سعرًا', 'No items in this category.': 'لا توجد منتجات في هذه الفئة.', Featured: 'مميّز', Limited: 'محدود', Owned: 'تم الشراء', Need: 'تحتاج إلى', 'Buy now': 'شراء الآن', 'Processing purchase…': 'جارٍ معالجة الشراء…', 'Purchase failed.': 'فشل الشراء.', 'Store is still unavailable. Try again shortly.': 'المتجر غير متاح حاليًا. حاول بعد قليل.',
  'TON Testnet connection and payment status': 'اتصال شبكة TON التجريبية وحالة الدفع', 'Restoring wallet…': 'جارٍ استعادة المحفظة…', 'Testnet wallet connected': 'المحفظة التجريبية متصلة', 'Connect TON Testnet wallet': 'ربط محفظة TON التجريبية', 'Connection is handled by the official TON Connect protocol.': 'يتم الاتصال عبر بروتوكول TON Connect الرسمي.', 'Open MTX inside Telegram before connecting a wallet.': 'افتح MTX داخل تيليجرام قبل ربط المحفظة.', 'Pay 0.01 TON · Get 100 MTX': 'ادفع 0.01 TON · احصل على 100 MTX', 'Verifying payment…': 'جارٍ التحقق من الدفع…', 'Check pending payment': 'فحص الدفعة المعلّقة', 'Checking…': 'جارٍ الفحص…', 'MTX is credited only after independent server-side blockchain verification.': 'تُضاف MTX فقط بعد تحقق مستقل من البلوكشين بواسطة الخادم.', Transactions: 'المعاملات', 'No verified TON transactions.': 'لا توجد معاملات TON مؤكدة.', 'Switch the connected wallet to TON Testnet.': 'حوّل المحفظة المتصلة إلى شبكة TON التجريبية.', 'Checking the pending transaction on TON Testnet…': 'جارٍ فحص المعاملة المعلّقة على شبكة TON التجريبية…', 'The transaction is still pending. No additional payment is needed.': 'المعاملة ما زالت معلّقة ولا حاجة إلى دفع إضافي.', 'Payment verification failed.': 'فشل التحقق من الدفع.', 'Creating a secure payment order…': 'جارٍ إنشاء طلب دفع آمن…', 'Transaction submitted. Waiting for Testnet confirmation…': 'تم إرسال المعاملة، بانتظار تأكيد الشبكة التجريبية…', 'Transaction submitted but still pending. Check again shortly.': 'تم إرسال المعاملة لكنها ما زالت معلّقة. افحصها بعد قليل.', 'Testnet payment failed.': 'فشلت الدفعة التجريبية.',
};
Object.assign(ar, { Notifications: 'الإشعارات', 'Game activity and official announcements': 'نشاط اللعبة والإعلانات الرسمية', 'Mark all read': 'تحديد الكل كمقروء', 'Open MTX inside Telegram to view notifications.': 'افتح MTX داخل تيليجرام لعرض الإشعارات.', 'Loading notifications…': 'جارٍ تحميل الإشعارات…', 'Notifications could not load.': 'تعذّر تحميل الإشعارات.', 'No notifications yet.': 'لا توجد إشعارات بعد.', Unread: 'غير مقروء', 'Upgrade activated': 'تم تفعيل الترقية', 'Purchase completed': 'اكتمل الشراء', 'Payment update': 'تحديث الدفع', 'Reward received': 'تم استلام المكافأة' });
Object.assign(ar, { 'Choose three cards in the correct order.': 'اختر ثلاث بطاقات بالترتيب الصحيح.', 'Selected combination': 'المجموعة المختارة', 'Tap upgrade': 'ترقية النقر', 'Energy upgrade': 'ترقية الطاقة', 'Profit upgrade': 'ترقية الأرباح', 'Aurora skin': 'مظهر الشفق', 'Recharge boost': 'معزز الشحن', 'Energy pack': 'حزمة الطاقة', 'Daily cipher answer': 'إجابة الرمز اليومي', 'Daily combo reward received.': 'تم استلام مكافأة المجموعة اليومية.', 'Combination is incorrect. Try a different order.': 'المجموعة غير صحيحة. جرّب ترتيبًا آخر.', 'Daily cipher reward received.': 'تم استلام مكافأة الرمز اليومي.', 'Cipher is incorrect. Try again.': 'الرمز غير صحيح. حاول مرة أخرى.', 'Checking…': 'جارٍ التحقق…', 'The current game name': 'اسم اللعبة الحالية' });
Object.assign(ar, { Achievements: 'الإنجازات', 'Badges earned through real game progress': 'شارات تُكتسب عبر التقدم الحقيقي في اللعبة', 'Achievements could not load.': 'تعذّر تحميل الإنجازات.', 'Loading achievements…': 'جارٍ تحميل الإنجازات…', Unlocked: 'تم فتحها' });
Object.assign(ar, { Global: 'العالمي', Friends: 'الأصدقاء', Weekly: 'الأسبوعي', Monthly: 'الشهري', Season: 'الموسم', 'Leaderboard period': 'فترة لوحة المتصدرين', 'Loading leaderboard…': 'جارٍ تحميل لوحة المتصدرين…', 'Invite friends to see them here.': 'ادعُ أصدقاءك ليظهروا هنا.', 'No ranking data for this period yet.': 'لا توجد بيانات ترتيب لهذه الفترة بعد.', You: 'أنت' });

export function useI18n() {
  const { language } = usePreferences();
  const fa = language === 'fa'; const arabic = language === 'ar';
  const text = useCallback((english: string, persian: string) => fa ? persian : arabic ? ar[english] ?? english : english, [arabic, fa]);
  const number = useCallback((value: number) => value.toLocaleString(fa ? 'fa-IR' : arabic ? 'ar-EG-u-nu-latn' : 'en-US'), [arabic, fa]);
  const date = useCallback((value: number) => new Date(value).toLocaleString(fa ? 'fa-IR' : arabic ? 'ar-EG-u-nu-latn-ca-gregory' : 'en-US'), [arabic, fa]);
  return { fa, ar: arabic, language, text, number, date };
}
