import { useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { adminLogout, createAdminEvent, fetchAdminAnomalies, fetchAdminDashboard, fetchAdminEvents, fetchAdminItems, fetchAdminLogs, fetchAdminNotifications, fetchAdminPayments, fetchAdminUsers, sendAdminNotification, setUserBan, type AdminAnomaly, type AdminDashboard, type AdminEvent, type AdminItem, type AdminLog, type AdminNotification, type AdminPayment, type AdminUser } from '../services/adminService';
import { useAppStore } from '../store/useAppStore';

type Tab = 'overview' | 'users' | 'payments' | 'security' | 'campaigns' | 'logs';
const tabs: { id: Tab; label: string }[] = [{ id: 'overview', label: 'Overview' }, { id: 'users', label: 'Users' }, { id: 'payments', label: 'Payments' }, { id: 'security', label: 'Security' }, { id: 'campaigns', label: 'Campaigns' }, { id: 'logs', label: 'Audit log' }];
const formatDate = (value: number) => new Date(value).toLocaleString();

export function AdminPage() {
  const navigate = useNavigate(); const setAuthenticated = useAppStore((state) => state.setAdminAuthenticated);
  const [tab, setTab] = useState<Tab>('overview'); const [dashboard, setDashboard] = useState<AdminDashboard>(); const [users, setUsers] = useState<AdminUser[]>([]); const [payments, setPayments] = useState<AdminPayment[]>([]); const [items, setItems] = useState<AdminItem[]>([]); const [anomalies, setAnomalies] = useState<AdminAnomaly[]>([]); const [events, setEvents] = useState<AdminEvent[]>([]); const [notifications, setNotifications] = useState<AdminNotification[]>([]); const [logs, setLogs] = useState<AdminLog[]>([]); const [search, setSearch] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const [noticeTitle, setNoticeTitle] = useState(''); const [noticeMessage, setNoticeMessage] = useState(''); const [eventTitle, setEventTitle] = useState(''); const [eventStart, setEventStart] = useState(''); const [eventEnd, setEventEnd] = useState(''); const [multiplier, setMultiplier] = useState('2');
  const load = async () => { setError(''); try { const values = await Promise.all([fetchAdminDashboard(), fetchAdminUsers(), fetchAdminPayments(), fetchAdminItems(), fetchAdminAnomalies(), fetchAdminEvents(), fetchAdminNotifications(), fetchAdminLogs()]); setDashboard(values[0]); setUsers(values[1]); setPayments(values[2]); setItems(values[3]); setAnomalies(values[4]); setEvents(values[5]); setNotifications(values[6]); setLogs(values[7]); } catch { setError('Admin data could not be loaded.'); } };
  useEffect(() => { void load(); const expired = () => { setAuthenticated(false); navigate('/admin/login', { replace: true }); }; window.addEventListener('mtx:admin-expired', expired); return () => window.removeEventListener('mtx:admin-expired', expired); }, []);
  const filteredUsers = useMemo(() => users.filter((user) => user.userId.toLowerCase().includes(search.toLowerCase())), [users, search]);
  const logout = () => { adminLogout(); setAuthenticated(false); navigate('/admin/login', { replace: true }); };
  const sendNotice = async () => { if (!noticeTitle.trim() || !noticeMessage.trim()) return; setBusy(true); try { await sendAdminNotification(noticeTitle.trim(), noticeMessage.trim()); setNoticeTitle(''); setNoticeMessage(''); await load(); } finally { setBusy(false); } };
  const createEvent = async () => { const startsAt = new Date(eventStart).getTime(); const endsAt = new Date(eventEnd).getTime(); const value = Number(multiplier); if (!eventTitle.trim() || !Number.isFinite(startsAt) || !Number.isFinite(endsAt) || endsAt <= startsAt || value < 1 || value > 10) { setError('Enter a valid event title, dates and multiplier.'); return; } setBusy(true); try { await createAdminEvent(eventTitle.trim(), startsAt, endsAt, value); setEventTitle(''); setEventStart(''); setEventEnd(''); await load(); } finally { setBusy(false); } };

  return <main className="admin-page"><header><div><h1>MTX Admin</h1><span>Restricted operator console</span></div><button className="button ghost" onClick={logout}>Sign out</button></header>
    {error && <p className="admin-error">{error}</p>}
    <nav className="admin-tabs">{tabs.map((item) => <button className={tab === item.id ? 'active' : ''} key={item.id} onClick={() => setTab(item.id)}>{item.label}</button>)}</nav>
    {tab === 'overview' && <><section className="admin-stats">{dashboard && Object.entries(dashboard.stats).map(([key, value]) => <article key={key}><strong>{value.toLocaleString()}</strong><span>{key.replace(/([A-Z])/g, ' $1')}</span></article>)}</section><section className="admin-grid"><article className="admin-panel"><h2>Store catalog</h2>{items.map((item) => <div className="admin-row" key={item.id}><span>{item.title}</span><small>{item.category}</small><strong>{item.price.toLocaleString()} MTX</strong></div>)}</article><article className="admin-panel"><h2>Recent activity</h2>{dashboard?.recentLogs.map((log) => <div className="admin-row" key={log.id}><span>{log.action}</span><small>{log.target || '—'}</small><time>{formatDate(log.createdAt)}</time></div>)}</article></section></>}
    {tab === 'users' && <section className="admin-panel"><header><h2>Users ({users.length})</h2><input placeholder="Search Telegram ID" value={search} onChange={(event) => setSearch(event.target.value)} /></header>{filteredUsers.map((user) => <div className={`admin-row ${user.banned ? 'banned' : ''}`} key={user.userId}><span>{user.userId}<small>{user.rank} · Level {user.level}</small></span><strong>{user.coins.toLocaleString()} MTX</strong><button className="button ghost" onClick={() => void setUserBan(user.userId, !user.banned).then(load)}>{user.banned ? 'Unban' : 'Ban'}</button></div>)}</section>}
    {tab === 'payments' && <section className="admin-panel"><h2>Payments ({payments.length})</h2>{payments.length === 0 ? <p className="muted">No payments recorded.</p> : payments.map((payment) => <div className="admin-row" key={payment.transactionId}><span>{payment.userId}<small>{payment.transactionId}</small></span><strong>{payment.amount} {payment.asset}</strong><span className={`payment-${payment.status}`}>{payment.status}</span></div>)}</section>}
    {tab === 'security' && <section className="admin-panel"><h2>Anti-cheat flags ({anomalies.length})</h2><p className="muted">Review flags manually. A flag does not automatically ban a player.</p>{anomalies.length === 0 ? <p className="admin-success">No suspicious activity recorded.</p> : anomalies.map((item, index) => <div className="admin-row" key={`${item.userId}:${item.at}:${index}`}><span>{item.userId}</span><strong>{item.type}</strong><time>{formatDate(item.at)}</time></div>)}</section>}
    {tab === 'campaigns' && <section className="admin-grid"><article className="admin-panel"><h2>Send notification</h2><input placeholder="Title" value={noticeTitle} onChange={(event) => setNoticeTitle(event.target.value)} /><textarea placeholder="Message" value={noticeMessage} onChange={(event) => setNoticeMessage(event.target.value)} /><button className="button primary" disabled={busy || !noticeTitle.trim() || !noticeMessage.trim()} onClick={() => void sendNotice()}>Send notification</button><h3>Recent notifications</h3>{notifications.slice(0, 10).map((item) => <div className="admin-row" key={item.id}><span>{item.title}</span><small>{item.message}</small><time>{formatDate(item.createdAt)}</time></div>)}</article><article className="admin-panel"><h2>Create event</h2><input placeholder="Event title" value={eventTitle} onChange={(event) => setEventTitle(event.target.value)} /><label>Starts<input type="datetime-local" value={eventStart} onChange={(event) => setEventStart(event.target.value)} /></label><label>Ends<input type="datetime-local" value={eventEnd} onChange={(event) => setEventEnd(event.target.value)} /></label><label>Multiplier<input type="number" min="1" max="10" step="0.1" value={multiplier} onChange={(event) => setMultiplier(event.target.value)} /></label><button className="button primary" disabled={busy} onClick={() => void createEvent()}>Create event</button><h3>Events</h3>{events.map((item) => <div className="admin-row" key={item.id}><span>{item.title}</span><strong>×{item.multiplier}</strong><small>{formatDate(item.startsAt)}</small></div>)}</article></section>}
    {tab === 'logs' && <section className="admin-panel"><h2>Immutable audit trail ({logs.length})</h2>{logs.map((log) => <div className="admin-row" key={log.id}><span>{log.action}<small>{log.adminId}</small></span><strong>{log.target || '—'}</strong><time>{formatDate(log.createdAt)}</time></div>)}</section>}
  </main>;
}
