import { Link } from 'react-router-dom';
import { useI18n } from '../hooks/useI18n';
import { usePreferences } from '../hooks/usePreferences';
import { updatePreferences, type AppPreferences, type LanguagePreference, type ThemePreference } from '../services/preferencesService';

function Toggle({ icon, title, description, setting, value }: { icon: string; title: string; description: string; setting: keyof Pick<AppPreferences, 'sound' | 'haptics' | 'lowPower'>; value: boolean }) {
  return <label className="settings-row"><span className="settings-icon">{icon}</span><span><strong>{title}</strong><small>{description}</small></span><input type="checkbox" checked={value} onChange={(event) => updatePreferences({ [setting]: event.target.checked })} /><i aria-hidden="true" /></label>;
}

export function SettingsPage() {
  const preferences = usePreferences(); const { text } = useI18n();
  const themes: Array<{ id: ThemePreference; en: string; fa: string; icon: string }> = [{ id: 'system', en: 'System', fa: 'سیستم', icon: '📱' }, { id: 'dark', en: 'Dark', fa: 'تیره', icon: '🌙' }, { id: 'light', en: 'Light', fa: 'روشن', icon: '☀️' }];
  const languages: Array<{ id: LanguagePreference; label: string }> = [{ id: 'en', label: 'English' }, { id: 'fa', label: 'فارسی' }, { id: 'ar', label: 'العربية' }];
  return <main className="page commerce-page"><Link className="brand" to="/">MTX</Link><header className="commerce-header"><div><h1>{text('Settings', 'تنظیمات')}</h1><p>{text('Saved automatically on this device', 'به‌صورت خودکار روی این دستگاه ذخیره می‌شود')}</p></div></header><section className="settings-card"><h2>{text('Language', 'زبان')}</h2><div className="language-options" role="radiogroup" aria-label={text('Interface language', 'زبان رابط')}>{languages.map((language) => <button className={preferences.language === language.id ? 'active' : ''} role="radio" aria-checked={preferences.language === language.id} type="button" key={language.id} onClick={() => updatePreferences({ language: language.id })}>{language.label}</button>)}</div></section><section className="settings-card"><h2>{text('Appearance', 'ظاهر')}</h2><div className="theme-options" role="radiogroup" aria-label={text('Color theme', 'پوسته رنگی')}>{themes.map((theme) => <button className={preferences.theme === theme.id ? 'active' : ''} role="radio" aria-checked={preferences.theme === theme.id} type="button" key={theme.id} onClick={() => updatePreferences({ theme: theme.id })}><span>{theme.icon}</span>{text(theme.en, theme.fa)}</button>)}</div></section><section className="settings-card"><h2>{text('Game feedback', 'بازخورد بازی')}</h2><Toggle icon="🔊" title={text('Tap sound', 'صدای تپ')} description={text('Play a short sound for each tap', 'برای هر تپ یک صدای کوتاه پخش شود')} setting="sound" value={preferences.sound} /><Toggle icon="📳" title={text('Vibration', 'لرزش')} description={text('Telegram haptic feedback while tapping', 'بازخورد لرزشی تلگرام هنگام تپ')} setting="haptics" value={preferences.haptics} /><Toggle icon="🔋" title={text('Low-power mode', 'حالت کم‌مصرف')} description={text('Reduce motion, glow and background effects', 'کاهش حرکت، درخشش و افکت پس‌زمینه')} setting="lowPower" value={preferences.lowPower} /></section></main>;
}
