import type { PostgresQueries } from './productionStorage.ts';
import type { ServerGameState } from './gameEngine.ts';

export interface SocialPersistence {
  daily(userId: string): Promise<{ day: string; streak: number } | null>;
  claimDaily(userId: string, day: string, yesterday: string, state: ServerGameState): Promise<{ streak: number; state: ServerGameState } | null>;
  missionClaimed(userId: string, missionId: string, periodKey: string): Promise<boolean>;
  claimMission(userId: string, missionId: string, periodKey: string, now: number, state: ServerGameState, reward: number): Promise<ServerGameState | null>;
  referralCount(userId: string): Promise<number>;
  referralNetwork(userId: string): Promise<string[]>;
  createReferral(referrerId: string, refereeId: string, deviceHash: string, now: number, referrer: ServerGameState, referee: ServerGameState): Promise<{ result: 'created' | 'referee-used' | 'device-used'; referrer?: ServerGameState; referee?: ServerGameState }>;
  challengeClaimed(userId: string, type: 'combo' | 'cipher', day: string): Promise<boolean>;
  claimChallenge(userId: string, type: 'combo' | 'cipher', day: string, reward: number, now: number, state: ServerGameState): Promise<ServerGameState | null>;
}

export class PostgresSocialPersistence implements SocialPersistence {
  private readonly database: PostgresQueries;
  constructor(database: PostgresQueries) { this.database = database; }
  async daily(userId: string): Promise<{ day: string; streak: number } | null> { const result = await this.database.query<{ day: string; streak: number }>('SELECT claim_day::text AS day, streak FROM mtx_daily_claims WHERE user_id = $1', [userId]); return result.rows[0] ?? null; }
  async claimDaily(userId: string, day: string, yesterday: string, state: ServerGameState): Promise<{ streak: number; state: ServerGameState } | null> { return this.inTransaction(async (database) => { await this.lockState(database, state); const result = await database.query<{ streak: number }>('INSERT INTO mtx_daily_claims (user_id, claim_day, streak) VALUES ($1, $2, 1) ON CONFLICT (user_id) DO UPDATE SET claim_day = EXCLUDED.claim_day, streak = CASE WHEN mtx_daily_claims.claim_day = $3::date THEN LEAST(7, mtx_daily_claims.streak + 1) ELSE 1 END WHERE mtx_daily_claims.claim_day <> EXCLUDED.claim_day RETURNING streak', [userId, day, yesterday]); const streak = result.rows[0]?.streak; if (!streak) return null; const updated = { ...state, coins: state.coins + streak * 100, version: state.version + 1 }; await this.saveState(database, updated); return { streak, state: updated }; }); }
  async missionClaimed(userId: string, missionId: string, periodKey: string): Promise<boolean> { const result = await this.database.query<{ exists: boolean }>('SELECT EXISTS (SELECT 1 FROM mtx_mission_claims WHERE user_id = $1 AND mission_id = $2 AND period_key = $3) AS exists', [userId, missionId, periodKey]); return Boolean(result.rows[0]?.exists); }
  async claimMission(userId: string, missionId: string, periodKey: string, now: number, state: ServerGameState, reward: number): Promise<ServerGameState | null> { return this.inTransaction(async (database) => { await this.lockState(database, state); const result = await database.query<{ user_id: string }>('INSERT INTO mtx_mission_claims (user_id, mission_id, period_key, claimed_at) VALUES ($1, $2, $3, $4) ON CONFLICT DO NOTHING RETURNING user_id', [userId, missionId, periodKey, new Date(now).toISOString()]); if (!result.rows.length) return null; const updated = { ...state, coins: state.coins + reward, version: state.version + 1 }; await this.saveState(database, updated); return updated; }); }
  async referralCount(userId: string): Promise<number> { const result = await this.database.query<{ count: string }>('SELECT COUNT(*)::text AS count FROM mtx_referrals WHERE referrer_id = $1', [userId]); return Number(result.rows[0]?.count ?? 0); }
  async referralNetwork(userId: string): Promise<string[]> { const result = await this.database.query<{ referrer_id: string; referee_id: string }>('SELECT referrer_id, referee_id FROM mtx_referrals WHERE referrer_id = $1 OR referee_id = $1', [userId]); return [...new Set(result.rows.flatMap((row) => [row.referrer_id, row.referee_id]).filter((id) => id !== userId))]; }
  async createReferral(referrerId: string, refereeId: string, deviceHash: string, now: number, referrer: ServerGameState, referee: ServerGameState): Promise<{ result: 'created' | 'referee-used' | 'device-used'; referrer?: ServerGameState; referee?: ServerGameState }> { return this.inTransaction(async (database) => { for (const state of [referrer, referee].sort((left, right) => left.userId.localeCompare(right.userId))) await this.lockState(database, state); const inserted = await database.query<{ referee_id: string }>('INSERT INTO mtx_referrals (referee_id, referrer_id, device_hash, created_at) VALUES ($1, $2, $3, $4) ON CONFLICT DO NOTHING RETURNING referee_id', [refereeId, referrerId, deviceHash, new Date(now).toISOString()]); if (!inserted.rows.length) { const usedReferee = await database.query<{ exists: boolean }>('SELECT EXISTS (SELECT 1 FROM mtx_referrals WHERE referee_id = $1) AS exists', [refereeId]); if (usedReferee.rows[0]?.exists) return { result: 'referee-used' }; return { result: 'device-used' }; } const updatedReferee = { ...referee, coins: referee.coins + 250, version: referee.version + 1 }; const updatedReferrer = { ...referrer, coins: referrer.coins + 500, version: referrer.version + 1 }; await this.saveState(database, updatedReferee); await this.saveState(database, updatedReferrer); return { result: 'created', referee: updatedReferee, referrer: updatedReferrer }; }); }
  async challengeClaimed(userId: string, type: 'combo' | 'cipher', day: string): Promise<boolean> { const result = await this.database.query<{ exists: boolean }>('SELECT EXISTS (SELECT 1 FROM mtx_challenge_claims WHERE user_id = $1 AND challenge_type = $2 AND challenge_day = $3) AS exists', [userId, type, day]); return Boolean(result.rows[0]?.exists); }
  async claimChallenge(userId: string, type: 'combo' | 'cipher', day: string, reward: number, now: number, state: ServerGameState): Promise<ServerGameState | null> { return this.inTransaction(async (database) => { await this.lockState(database, state); const result = await database.query<{ user_id: string }>('INSERT INTO mtx_challenge_claims (user_id, challenge_type, challenge_day, reward, claimed_at) VALUES ($1, $2, $3, $4, $5) ON CONFLICT DO NOTHING RETURNING user_id', [userId, type, day, reward, new Date(now).toISOString()]); if (!result.rows.length) return null; const updated = { ...state, coins: state.coins + reward, version: state.version + 1 }; await this.saveState(database, updated); return updated; }); }
  private async lockState(database: PostgresQueries, state: ServerGameState): Promise<void> { const result = await database.query<{ state: ServerGameState }>('SELECT state FROM mtx_game_state WHERE user_id = $1 FOR UPDATE', [state.userId]); const storedVersion = result.rows[0]?.state.version; if (storedVersion !== undefined && storedVersion !== state.version) throw new Error('STATE_VERSION_CONFLICT'); }
  private async saveState(database: PostgresQueries, state: ServerGameState): Promise<void> { await database.query('INSERT INTO mtx_game_state (user_id, state, updated_at) VALUES ($1, $2, NOW()) ON CONFLICT (user_id) DO UPDATE SET state = EXCLUDED.state, updated_at = NOW()', [state.userId, JSON.stringify(state)]); }
  private async inTransaction<T>(operation: (database: PostgresQueries) => Promise<T>): Promise<T> { if (!this.database.transaction) throw new Error('POSTGRES_TRANSACTIONS_REQUIRED'); return this.database.transaction(operation); }
}
